VARCHAR_MEDIUM = "VARCHAR(50)"
VARCHAR_LONG = "VARCHAR(255)"
VARCHAR_SHORT = "VARCHAR(10)"
INT = "INTEGER"
DATE = "DATE"
BOOL = "BOOLEAN"

SCHEMA_STR = f"""
    CREATE SCHEMA fifa;
"""
TABLE_STR = f"""
CREATE TABLE fifa.data (
    id SERIAL,
    year {INT} NOT NULL,
    sofifa_id {INT},
    player_url {VARCHAR_LONG},
    short_name {VARCHAR_MEDIUM},
    long_name {VARCHAR_MEDIUM},
    player_positions {VARCHAR_MEDIUM},
    overall {INT},
    potential {INT},
    value_eur {INT},
    wage_eur {INT},
    age {INT},
    dob {DATE},
    height_cm {INT},
    weight_kg {INT},
    club_team_id {INT},
    club_name {VARCHAR_LONG},
    league_name {VARCHAR_LONG},
    league_level {INT},
    club_position {VARCHAR_SHORT},
    club_jersey_number {INT},
    club_loaned_from {VARCHAR_MEDIUM},
    club_joined {DATE},
    club_contract_valid_until {INT},
    nationality_id {INT},
    nationality_name {VARCHAR_MEDIUM},
    nation_team_id {INT},
    nation_position {VARCHAR_SHORT},
    nation_jersey_number {INT},
    preferred_foot {VARCHAR_SHORT},
    weak_foot {INT},
    skill_moves {INT},
    international_reputation {INT},
    work_rate {VARCHAR_MEDIUM},
    body_type {VARCHAR_MEDIUM},
    real_face {BOOL},
    release_clause_eur {INT},
    player_tags {VARCHAR_LONG},
    player_traits {VARCHAR_LONG},
    pace {INT},
    shooting {INT},
    passing {INT},
    dribbling {INT},
    defending {INT},
    physic {INT}, 
    attacking_crossing {INT},
    attacking_finishing {INT},
    attacking_heading_accuracy {INT},
    attacking_short_passing {INT},
    attacking_volleys {INT},
    skill_dribbling {INT},
    skill_curve {INT},
    skill_fk_accuracy {INT},
    skill_long_passing {INT},
    skill_ball_control {INT},
    movement_acceleration {INT},
    movement_sprint_speed {INT},
    movement_agility {INT},
    movement_reactions {INT},
    movement_balance {INT},
    power_shot_power {INT},
    power_jumping {INT},
    power_stamina {INT},
    power_strength {INT},
    power_long_shots {INT},
    mentality_aggression {INT},
    mentality_interceptions {INT},
    mentality_positioning {INT},
    mentality_vision {INT},
    mentality_penalties {INT},
    mentality_composure {INT},
    defending_marking_awareness {INT},
    defending_standing_tackle {INT},
    defending_sliding_tackle {INT},
    goalkeeping_diving {INT},
    goalkeeping_handling {INT},
    goalkeeping_kicking {INT},
    goalkeeping_positioning {INT},
    goalkeeping_reflexes {INT},
    goalkeeping_speed {INT},
    ls {VARCHAR_SHORT},
    st {VARCHAR_SHORT},
    rs {VARCHAR_SHORT},
    lw {VARCHAR_SHORT},
    lf {VARCHAR_SHORT},
    cf {VARCHAR_SHORT},
    rf {VARCHAR_SHORT},
    rw {VARCHAR_SHORT},
    lam {VARCHAR_SHORT},
    cam {VARCHAR_SHORT},
    ram {VARCHAR_SHORT},
    lm {VARCHAR_SHORT},
    lcm {VARCHAR_SHORT},
    cm {VARCHAR_SHORT},
    rcm {VARCHAR_SHORT},
    rm {VARCHAR_SHORT},
    lwb {VARCHAR_SHORT},
    ldm {VARCHAR_SHORT},
    cdm {VARCHAR_SHORT},
    rdm {VARCHAR_SHORT},
    rwb {VARCHAR_SHORT},
    lb {VARCHAR_SHORT},
    lcb {VARCHAR_SHORT},
    cb {VARCHAR_SHORT},
    rcb {VARCHAR_SHORT},
    rb {VARCHAR_SHORT},
    gk {VARCHAR_SHORT},
    player_face_url {VARCHAR_LONG}, 
    club_logo_url {VARCHAR_LONG},
    club_flag_url {VARCHAR_LONG},
    nation_logo_url {VARCHAR_LONG},
    nation_flag_url {VARCHAR_LONG}
);
"""
